"""Concurrent-safe Jupyter KernelClient

Docs: https://AnswerDotAI.github.io/conkernelclient/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['DeadKernelError', 'apply_session_patch', 'ConKernelClient', 'ConKernelManager']

# %% ../nbs/00_core.ipynb #d3b521c0
from jupyter_client import AsyncKernelClient, AsyncKernelManager
from jupyter_client.session import Session
from zmq.error import ZMQError
from traitlets import Type, default
import asyncio, zmq.asyncio, time, logging

# %% ../nbs/00_core.ipynb #737a0fc1
_log = logging.getLogger(__name__)

# %% ../nbs/00_core.ipynb #a093006c
class DeadKernelError(Exception): pass

# %% ../nbs/00_core.ipynb #374b75d0
def _send(self, stream, msg_or_type, content=None, parent=None, ident=None,
    buffers=None, track=False, header=None, metadata=None):
    msg = self._orig_send(stream, msg_or_type, content=content, parent=parent,
        ident=ident, buffers=buffers, track=track, header=header, metadata=metadata)
    # Session.send sends via a SYNC shadow of the asyncio socket (zmq.Socket.shadow), which runs
    # libzmq process_commands() and consumes the FD edge a buffered reply may have signalled —
    # a recv parked in poll(None) on that edge would then sleep forever. Reading EVENTS through
    # the async override (_AsyncSocket.get) makes pyzmq re-schedule _handle_events for pending
    # recv/poll futures, compensating the consumed edge. It MUST be .get(): pyzmq aliases
    # `getsockopt = SocketBase.get` at class level, so .getsockopt() bypasses the override
    # and consumes the edge without rescheduling.
    if stream:
        if hasattr(stream, 'io_thread'): stream.io_thread.socket.get(zmq.EVENTS)
        # See tests/zmq_regression.py for a regression test which fails is 'get' is switched to 'getsockopt'
        elif hasattr(stream, 'get'): stream.get(zmq.EVENTS)
    return msg

def apply_session_patch():
    "Make `Session.send` compensate the ZMQ FD edge a sync send consumes (see `_send` comment). Idempotent; applied automatically when a `ConKernelClient` is constructed, and available for use with vanilla clients."
    if hasattr(Session, '_orig_send'): return
    Session._orig_send = Session.send
    Session.send = _send

# %% ../nbs/00_core.ipynb #d6a5fa6a
class ConKernelClient(AsyncKernelClient):
    def __init__(self, *args, **kwargs):
        apply_session_patch()
        # jupyter_client's `get_connection_info` returns curve keys as str, but the client traits are `Bytes`
        for k in ('curve_publickey','curve_secretkey'):
            if isinstance(kwargs.get(k), str): kwargs[k] = kwargs[k].encode()
        super().__init__(*args, **kwargs)

    def _fail_pending(self, exc:Exception, skip=None):
        for k,(q,_) in list(getattr(self, '_pending', {}).items()):
            if k != skip:
                try: q.put_nowait(exc)
                except asyncio.QueueFull: pass

    def _check_alive(self):
        if not self.channels_running: raise RuntimeError("Channels not running")
        tk = getattr(self, '_shell_reader_task', None)
        return tk is not None and not tk.done()

    async def start_channels(self, shell:bool=True, iopub:bool=True, stdin:bool=True, hb:bool=True, control:bool=True):
        "Start channels, wait for ready, and launch background shell-reply reader"
        super().start_channels(shell=shell, iopub=iopub, stdin=stdin, hb=hb, control=control)
        await self.wait_for_ready()
        self._pending = {}
        _ready = asyncio.Event()
        async def _reader():
            _ready.set()
            while True:
                try: reply = await self.get_shell_msg(timeout=None)
                except Exception as e:
                    if isinstance(e, (AssertionError, OSError, ZMQError)): e = DeadKernelError(f"Kernel socket closed: {e}")
                    self._fail_pending(e)
                    _log.warning(f"_reader died, pending={list(self._pending)}: {e}")
                    break
                mid = reply["parent_header"].get("msg_id")
                pend = self._pending.get(mid)
                if pend:
                    q, soe = pend
                    try: q.put_nowait(reply)
                    except asyncio.QueueFull: pass
                cts = reply.get("content", {})
                if cts.get("status") in ("error", "aborted") and pend and soe:
                    exc = RuntimeError(f"Kernel error aborted: {cts.get('ename')}: {cts.get('evalue')}")
                    self._fail_pending(exc, skip=mid)
        self._shell_reader_task = asyncio.create_task(_reader())
        await _ready.wait()
        await asyncio.sleep(0.2)
        return self

    def stop_channels(self):
        "Stop channels and cancel the background shell-reply reader task"
        self._fail_pending(RuntimeError("Shell channels stopped before reply"))
        super().stop_channels()
        if (tk := getattr(self, '_shell_reader_task', None)):
            tk.cancel()
            self._shell_reader_task = None
        time.sleep(0.2)

    async def _async_recv_reply(self, msg_id, timeout=None, channel="shell"):
        if channel == "control": return await self._async_get_control_msg(timeout=timeout)
        q, _ = self._pending[msg_id]
        try:
            res = await asyncio.wait_for(q.get(), timeout)
            if isinstance(res, Exception): raise res
            return res
        finally: self._pending.pop(msg_id, None)

    def execute(self, code, user_expressions=None, allow_stdin=None, reply=False, subsh_id=None,
        cts_typ='code', timeout=60, msg_id=None, stop_on_error=True, fail_pending=False, **kw):
        "Send an execute request, returning a coroutine for the reply if `reply`, else the msg_id"
        if not self._check_alive(): return asyncio.sleep(0) if reply else None
        if user_expressions is None: user_expressions = {}
        if allow_stdin is None: allow_stdin = self.allow_stdin
        content = dict(user_expressions=user_expressions, allow_stdin=allow_stdin, subsh_id=subsh_id, stop_on_error=stop_on_error, **kw)
        content[cts_typ] = code
        msg = self.session.msg("execute_request", content)
        if msg_id is not None: msg["header"]["msg_id"] = msg_id
        if subsh_id is not None: msg["header"]["subshell_id"] = subsh_id
        msg_id = msg["header"]["msg_id"]
        if reply: self._pending[msg_id] = (asyncio.Queue(maxsize=1), stop_on_error if fail_pending is None else fail_pending)
        try: self.shell_channel.send(msg)
        except (AssertionError, OSError, ZMQError) as e: raise DeadKernelError(f"Kernel socket closed: {e}") from e
        if not reply: return msg_id
        return self._async_recv_reply(msg_id, timeout=timeout)

    async def stdin_send(self, msg:dict):
        "Send on `stdin_channel` then ping event loop"
        try: self.stdin_channel.send(msg)
        except (AssertionError, OSError, ZMQError) as e: raise DeadKernelError(f"Kernel socket closed: {e}") from e
        await asyncio.sleep(0.01)

# %% ../nbs/00_core.ipynb #b828c222
class ConKernelManager(AsyncKernelManager):
    client_class,client_factory = ConKernelClient,Type(ConKernelClient)
    @default('transport_encryption')
    def _transport_encryption_default(self): return 'auto'
