"""Concurrent-safe Jupyter KernelClient

Docs: https://AnswerDotAI.github.io/conkernelclient/core.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['apply_session_patch', 'ConKernelClient', 'ConKernelManager']

# %% ../nbs/00_core.ipynb #d3b521c0
from jupyter_client import AsyncKernelClient, AsyncKernelManager
from jupyter_client.session import Session
from zmq.error import ZMQError
from traitlets import Type, default
from fastcore.utils import patch
from jupywire.ops import EvalOps
from jupywire.route import RouterOps, DeadKernelError
from queue import Empty
import asyncio, inspect, zmq.asyncio, time, logging

# %% ../nbs/00_core.ipynb #737a0fc1
_log = logging.getLogger(__name__)

# %% ../nbs/00_core.ipynb #374b75d0
def _send(self, stream, msg_or_type, content=None, parent=None, ident=None,
    buffers=None, track=False, header=None, metadata=None):
    msg = self._orig_send(stream, msg_or_type, content=content, parent=parent,
        ident=ident, buffers=buffers, track=track, header=header, metadata=metadata)
    # Session.send sends via a SYNC shadow of the asyncio socket (zmq.Socket.shadow), which runs
    # libzmq process_commands() and consumes the FD edge a buffered reply may have signalled —
    # a recv parked in poll(None) on that edge would then sleep forever. Reading EVENTS through
    # the async override (_AsyncSocket.get) makes pyzmq re-schedule _handle_events for pending
    # recv/poll futures, compensating the consumed edge. It MUST be .get(): pyzmq aliases
    # `getsockopt = SocketBase.get` at class level, so .getsockopt() bypasses the override
    # and consumes the edge without rescheduling.
    if stream:
        if hasattr(stream, 'io_thread'): stream.io_thread.socket.get(zmq.EVENTS)
        # See tests/zmq_regression.py for a regression test which fails is 'get' is switched to 'getsockopt'
        elif hasattr(stream, 'get'): stream.get(zmq.EVENTS)
    return msg

def apply_session_patch():
    "Make `Session.send` compensate the ZMQ FD edge a sync send consumes (see `_send` comment). Idempotent; applied automatically when a `ConKernelClient` is constructed, and available for use with vanilla clients."
    if hasattr(Session, '_orig_send'): return
    Session._orig_send = Session.send
    Session.send = _send

# %% ../nbs/00_core.ipynb #d6a5fa6a
def _dead_status():
    "The dead `status` rustygate broadcasts, synthesized client-side for zmq transport loss and heartbeat silence"
    return dict(channel='iopub', msg_type='status', header={}, parent_header={}, content=dict(execution_state='dead'), buffers=[])


class ConKernelClient(RouterOps, EvalOps, AsyncKernelClient):
    def __init__(self, *args, **kwargs):
        apply_session_patch()
        # jupyter_client's `get_connection_info` returns curve keys as str, but the client traits are `Bytes`
        for k in ('curve_publickey','curve_secretkey'):
            if isinstance(kwargs.get(k), str): kwargs[k] = kwargs[k].encode()
        super().__init__(*args, **kwargs)

    def _check_alive(self):
        if not self.channels_running: raise RuntimeError("Channels not running")
        pumps = getattr(self, '_pumps', None)
        if not pumps or any(t.done() for t in pumps): raise DeadKernelError('kernel died')

# %% ../nbs/00_core.ipynb #fd6e6aa9
@patch
async def _route(self:ConKernelClient, msg):
    r = self.route(msg)
    if inspect.isawaitable(r): await r

@patch
async def _pump(self:ConKernelClient, name):
    "Drain one zmq channel into the router; a socket error is transport loss, delivered as the dead status."
    ch = getattr(self, f'{name}_channel')
    try:
        while True: await self._route(dict(await ch.get_msg(timeout=None), channel=name))
    except asyncio.CancelledError: raise
    except Exception as e:
        _log.warning(f"{name} pump died: {e}")
        await self._route(_dead_status())

@patch
async def _watch_hb(self:ConKernelClient):
    "Declare death after three consecutive unanswered heartbeat echoes; the kernel echoes from a dedicated thread, so sustained silence means the process is gone."
    misses = 0
    while True:
        await asyncio.sleep(self.hb_channel.time_to_dead)
        misses = 0 if self.hb_channel.is_beating() else misses + 1
        if misses >= 3: return await self._route(_dead_status())

# %% ../nbs/00_core.ipynb #394db3b2
@patch
async def start_channels(self:ConKernelClient, shell:bool=True, iopub:bool=True, stdin:bool=True, hb:bool=True, control:bool=True):
    "Start channels, wait for ready, then launch the router pumps and the heartbeat watcher"
    super(ConKernelClient, self).start_channels(shell=shell, iopub=iopub, stdin=stdin, hb=hb, control=control)
    await self.wait_for_ready()
    self._init_router()
    chans = [c for c, on in (('shell',shell), ('iopub',iopub), ('stdin',stdin), ('control',control)) if on]
    self._pumps = [asyncio.create_task(self._pump(c)) for c in chans]
    if hb: self._pumps.append(asyncio.create_task(self._watch_hb()))
    return self

@patch
def stop_channels(self:ConKernelClient):
    "Stop channels and cancel the router pumps"
    if getattr(self, '_pumps', None): self.fail_waiters(RuntimeError("Channels stopped before reply"))
    super(ConKernelClient, self).stop_channels()
    for t in getattr(self, '_pumps', []): t.cancel()
    self._pumps = []

# %% ../nbs/00_core.ipynb #a930c688
@patch
def send(self:ConKernelClient, msg, channel):
    "Transmit a built message dict on `channel` (buffers ride as extra frames); a closed socket raises `DeadKernelError`."
    ch = getattr(self, f'{channel}_channel')
    try:
        if msg.get('buffers'): self.session.send(ch.socket, msg, buffers=msg['buffers'])
        else: ch.send(msg)
    except (AssertionError, OSError, ZMQError) as e: raise DeadKernelError(f"Kernel socket closed: {e}") from e

@patch
def execute(self:ConKernelClient, code, silent=False, store_history=True, user_expressions=None, allow_stdin=None, stop_on_error=True,
    msg_id=None, metadata=None, subshell_id=None, buffers=None):
    "Send an `execute_request`, fire-and-forget; returns its msg_id"
    self._check_alive()
    if user_expressions is None: user_expressions = {}
    if allow_stdin is None: allow_stdin = self.allow_stdin
    msg = self.session.msg("execute_request", dict(code=code, silent=silent, store_history=store_history,
        user_expressions=user_expressions, allow_stdin=allow_stdin, stop_on_error=stop_on_error), metadata=metadata)
    if buffers: msg["buffers"] = buffers
    if msg_id is not None: msg["header"]["msg_id"] = msg_id
    if subshell_id is not None: msg["header"]["subshell_id"] = subshell_id
    self.send(msg, 'shell')
    return msg["header"]["msg_id"]

# %% ../nbs/00_core.ipynb #3771c654
@patch
async def wait_for_ready(self:ConKernelClient, timeout=None):
    "Wait for the kernel to be ready: deterministic via `iopub_welcome` (JEP 65) when the kernel sends one, else jupyter_client's probe loop"
    deadline = time.monotonic()+timeout if timeout is not None else None
    def _left():
        if deadline is None: return 1.0
        t = deadline-time.monotonic()
        if t <= 0: raise RuntimeError(f"Kernel didn't respond in {timeout} seconds")
        return min(t, 1.0)
    async def _get(ch):
        while True:
            try: return await ch.get_msg(timeout=_left())
            except Empty:
                if not await self._async_is_alive(): raise RuntimeError("Kernel died before replying to kernel_info")
    msg = None
    while msg is None:
        self.kernel_info()
        try: msg = await self.iopub_channel.get_msg(timeout=_left())
        except Empty:
            if not await self._async_is_alive(): raise RuntimeError("Kernel died before replying to kernel_info")
    if msg['msg_type']=='iopub_welcome':
        mid = self.kernel_info()
        while (reply := await _get(self.shell_channel))['parent_header'].get('msg_id') != mid: pass
        self._handle_kernel_info_reply(reply)
        while not (msg['msg_type']=='status' and msg['parent_header'].get('msg_id')==mid and msg['content']['execution_state']=='idle'):
            msg = await _get(self.iopub_channel)
    else:
        while (reply := await _get(self.shell_channel))['msg_type'] != 'kernel_info_reply': pass
        self._handle_kernel_info_reply(reply)
        while True:
            try: await self.iopub_channel.get_msg(timeout=0.2)
            except Empty: break

# %% ../nbs/00_core.ipynb #967c10a1
@patch
async def astop_channels(self:ConKernelClient):
    "Stop channels and cancel the router pumps, awaiting their exit"
    if getattr(self, '_pumps', None): self.fail_waiters(RuntimeError("Channels stopped before reply"))
    for t in getattr(self, '_pumps', []):
        t.cancel()
        try: await t
        except asyncio.CancelledError: pass
    self._pumps = []
    super(ConKernelClient, self).stop_channels()

# %% ../nbs/00_core.ipynb #b828c222
class ConKernelManager(AsyncKernelManager):
    client_class,client_factory = ConKernelClient,Type(ConKernelClient)
    def __init__(self, *args, kernel_spec=None, **kwargs):
        super().__init__(*args, **kwargs)
        if kernel_spec is not None: self._kernel_spec = kernel_spec
    @default('transport_encryption')
    def _transport_encryption_default(self): return 'auto'
