"""Standard async operations on a running kernel, for `ConKernelClient`

Docs: https://AnswerDotAI.github.io/conkernelclient/ops.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ops.ipynb.

# %% auto #0
__all__ = ['default_timeout', 'iter_timeout', 'iopub_streams', 'run_kernel', 'reconnect']

# %% ../nbs/01_ops.ipynb #23936f1c
from fastcore.utils import *
from .core import ConKernelClient, ConKernelManager, DeadKernelError
from jupywire.ops import parent_id, iopub_msgs
from jupyter_client.kernelspec import KernelSpec
from contextlib import asynccontextmanager
from queue import Empty
import time


# %% ../nbs/01_ops.ipynb #d62f6b51
default_timeout = 10

def iter_timeout(timeout=None, default=default_timeout):
    "Yield remaining seconds until `timeout` expires, using monotonic time"
    end = time.monotonic() + (timeout or default)
    while (rem := end - time.monotonic()) > 0: yield rem

# %% ../nbs/01_ops.ipynb #ad596b2b
@patch
async def exec_drain(self:ConKernelClient, code, timeout=default_timeout, **kw):
    "Execute `code`; return `(reply, outputs)` where outputs are the request's iopub messages"
    msgs = await self.run(code, timeout=timeout, **kw)
    reply = next(m for m in msgs if m['msg_type'] == 'execute_reply')
    return reply, [m for m in msgs if m['channel'] == 'iopub']

# %% ../nbs/01_ops.ipynb #113e926f
@patch
async def iopub_drain(self:ConKernelClient, msg_id, timeout=default_timeout):
    "Collect unmatched iopub messages parented to `msg_id` from the attached `JmsgQueues` until its idle status arrives. Other requests' messages are discarded: one drain at a time"
    res = []
    for rem in iter_timeout(timeout):
        try: msg = await self.jmsgq.get('iopub', timeout=rem)
        except Empty: continue
        if parent_id(msg) != msg_id: continue
        res.append(msg)
        if msg.get('msg_type') == 'status' and nested_idx(msg, 'content', 'execution_state') == 'idle': return res
    raise TimeoutError(f"iopub idle not seen for {msg_id}")

# %% ../nbs/01_ops.ipynb #e705c283
@patch
async def iopub_flush(self:ConKernelClient, timeout=0.1):
    "Discard pending iopub messages from the attached `JmsgQueues`, e.g. leftovers from fire-and-forget executes"
    try:
        while True: await self.jmsgq.get('iopub', timeout=timeout)
    except Empty: pass

# %% ../nbs/01_ops.ipynb #ebdbd6eb
def iopub_streams(msgs, name=None):
    "The stream messages in `msgs`, optionally only stream `name` ('stdout'/'stderr')"
    streams = iopub_msgs(msgs, 'stream')
    return streams if name is None else [m for m in streams if m['content'].get('name') == name]

# %% ../nbs/01_ops.ipynb #52e7c8f1
@patch
async def exec_ok(self:ConKernelClient, code, timeout=default_timeout, **kw):
    "`exec_drain`, asserting the reply status is ok"
    reply, outputs = await self.exec_drain(code, timeout=timeout, **kw)
    assert reply['content']['status'] == 'ok', reply['content']
    return reply, outputs

# %% ../nbs/01_ops.ipynb #5de02acb
@patch
def _pre_ipy(self:ConKernelClient):
    if not self.shell_channel.is_alive(): raise DeadKernelError()


# %% ../nbs/01_ops.ipynb #aafc1ab4
@patch
def shell_request(self:ConKernelClient, msg_type, timeout=default_timeout, msg_id=None, subshell_id=None, metadata=None, buffers=None, **content):
    "A named shell request, content as keyword arguments; returns an awaitable of its reply"
    return self.request(msg_type, content, timeout=timeout, msg_id=msg_id, subshell_id=subshell_id, metadata=metadata, buffers=buffers)

@patch
def control_request(self:ConKernelClient, msg_type, timeout=default_timeout, **content):
    "A named control request, content as keyword arguments; returns an awaitable of its reply"
    return self.request(msg_type, content, channel='control', timeout=timeout)

# %% ../nbs/01_ops.ipynb #4f01d2b6
@patch
async def input_reply(self:ConKernelClient, value:str):
    "Answer the kernel's pending input_request (from `input()` in an execute sent with `allow_stdin=True`)"
    self.input(value)


# %% ../nbs/01_ops.ipynb #97d75b1e
class _ReqProxy:
    "Attribute access to protocol requests: `kc.cmd.complete(code=...)` sends `complete_request` on shell"
    def __init__(self, kc, send, suffix='_request'): self.kc,self.send,self.suffix = kc,send,suffix
    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        def _call(*, timeout=default_timeout, **content): return self.send(f"{name}{self.suffix}", timeout=timeout, **content)
        return _call

@patch(as_prop=True)
def cmd(self:ConKernelClient):
    "Shell requests as methods: `await kc.cmd.history(...)` sends `history_request`"
    return _ReqProxy(self, self.shell_request)

@patch(as_prop=True)
def ctl(self:ConKernelClient):
    "Control requests as methods: `await kc.ctl.shutdown(restart=True)` sends `shutdown_request`"
    return _ReqProxy(self, self.control_request)

# %% ../nbs/01_ops.ipynb #af8183ea
class _DapProxy:
    "DAP requests as methods: `kc.dap.stackTrace(threadId=1)` sends a `debug_request` on control"
    def __init__(self, kc): self.kc,self.seq = kc,0
    def __getattr__(self, command):
        if command.startswith('_'): raise AttributeError(command)
        if command.endswith('_') and not command.endswith('__'): command = command[:-1]
        async def _call(*, timeout=default_timeout, full=False, **arguments):
            self.seq += 1
            r = await self.kc.control_request('debug_request', timeout=timeout,
                type='request', seq=self.seq, command=command, arguments=arguments)
            return r if full else r['content']
        return _call

@patch(as_prop=True)
def dap(self:ConKernelClient):
    "DAP debug requests as methods. Stateful (`seq` counter), so cached per client, unlike `cmd`/`ctl`"
    if getattr(self, '_dap', None) is None: self._dap = _DapProxy(self)
    return self._dap

# %% ../nbs/01_ops.ipynb #8b1967f4
@patch
async def interrupt(self:ConKernelClient, timeout=5):
    "Interrupt the running request via `interrupt_request` on control; returns the reply"
    return await self.control_request('interrupt_request', timeout=timeout)

# %% ../nbs/01_ops.ipynb #edaf42c9
@asynccontextmanager
async def run_kernel(
    kernel_name='python3', # Kernelspec name to launch, or display name when `argv` is given
    argv=None, # Kernel argv; bypasses kernelspec discovery when provided
    manager_cls=ConKernelManager, # Manager class, e.g. a subclass customizing launch
    **kwargs # Passed to `start_kernel` (e.g. `env`, `cwd`)
):
    "Start a named or direct-argv kernel, yielding `(km, kc)`, and always shut it down"
    manager_kwargs = dict(kernel_name=kernel_name)
    if argv is not None: manager_kwargs['kernel_spec'] = KernelSpec(argv=argv, display_name=kernel_name)
    km = manager_cls(**manager_kwargs)
    await km.start_kernel(**kwargs)
    kc = await km.client().start_channels()
    try: yield km, kc
    finally:
        kc.stop_channels()
        await km.shutdown_kernel(now=True)

# %% ../nbs/01_ops.ipynb #839e20f6
async def reconnect(km, kc=None):
    "Restart `km`'s kernel (fresh process, state discarded) and return a newly connected client, stopping `kc` if given"
    if kc is not None: kc.stop_channels()
    await km.restart_kernel(now=True)
    return await km.client().start_channels()
