"""Standard async operations on a running kernel, for `ConKernelClient`

Docs: https://AnswerDotAI.github.io/conkernelclient/ops.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_ops.ipynb.

# %% auto #0
__all__ = ['default_timeout', 'output_types', 'parent_id', 'iter_timeout', 'nb_outputs', 'iopub_msgs', 'iopub_streams',
           'EvalError', 'parse_expr', 'run_kernel', 'reconnect']

# %% ../nbs/01_ops.ipynb #23936f1c
from fastcore.utils import *
from .core import ConKernelClient, ConKernelManager
from contextlib import asynccontextmanager
from ast import literal_eval
from queue import Empty
import asyncio, time

# %% ../nbs/01_ops.ipynb #d62f6b51
default_timeout = 10

def parent_id(msg):
    "The `msg_id` of the request this `msg` responds to, or None"
    return nested_idx(msg, "parent_header", "msg_id") or None

def iter_timeout(timeout=None, default=default_timeout):
    "Yield remaining seconds until `timeout` expires, using monotonic time"
    end = time.monotonic() + (timeout or default)
    while (rem := end - time.monotonic()) > 0: yield rem

# %% ../nbs/01_ops.ipynb #ad596b2b
@patch
async def iopub_drain(self:ConKernelClient, msg_id, timeout=default_timeout):
    "Collect iopub messages parented to `msg_id` until its idle status arrives. Other requests' messages are discarded: one drain at a time"
    res = []
    for rem in iter_timeout(timeout):
        try: msg = await self.get_iopub_msg(timeout=rem)
        except Empty: continue
        if parent_id(msg) != msg_id: continue
        res.append(msg)
        if msg.get('msg_type') == 'status' and nested_idx(msg, 'content', 'execution_state') == 'idle': return res
    raise TimeoutError(f"iopub idle not seen for {msg_id}")

# %% ../nbs/01_ops.ipynb #e705c283
@patch
async def iopub_flush(self:ConKernelClient, timeout=0.1):
    "Discard all pending iopub messages, e.g. leftovers from fire-and-forget executes"
    try:
        while True: await self.get_iopub_msg(timeout=timeout)
    except Empty: pass

# %% ../nbs/01_ops.ipynb #add288fe
output_types = {'stream', 'execute_result', 'display_data', 'error'}

def nb_outputs(msgs):
    "Convert iopub `msgs` to nbformat-style output dicts, dropping non-output messages"
    res = []
    for m in msgs:
        if (mt := m['msg_type']) not in output_types: continue
        d = dict(output_type=mt, **m['content'])
        d.pop('transient', None)
        res.append(d)
    return res

# %% ../nbs/01_ops.ipynb #ebdbd6eb
def iopub_msgs(msgs, msg_type=None):
    "Filter iopub `msgs` by `msg_type` - a single type, or a collection of types (all messages if None)"
    if msg_type is None: return msgs
    types = {msg_type} if isinstance(msg_type, str) else msg_type
    return [m for m in msgs if m['msg_type'] in types]

def iopub_streams(msgs, name=None):
    "The stream messages in `msgs`, optionally only stream `name` ('stdout'/'stderr')"
    streams = iopub_msgs(msgs, 'stream')
    return streams if name is None else [m for m in streams if m['content'].get('name') == name]

# %% ../nbs/01_ops.ipynb #52e7c8f1
@patch
async def exec_drain(self:ConKernelClient, code, timeout=default_timeout, **kw):
    "Execute `code`; return `(reply, outputs)` where outputs are the request's iopub messages"
    reply = await self.execute(code, reply=True, timeout=timeout, **kw)
    return reply, await self.iopub_drain(parent_id(reply), timeout=timeout)

@patch
async def exec_ok(self:ConKernelClient, code, timeout=default_timeout, **kw):
    "`exec_drain`, asserting the reply status is ok"
    reply, outputs = await self.exec_drain(code, timeout=timeout, **kw)
    assert reply['content']['status'] == 'ok', reply['content']
    return reply, outputs

@patch
async def exec_outs(self:ConKernelClient, code, timeout=default_timeout, **kw):
    "Execute `code` and return just its nbformat-style outputs"
    reply, outputs = await self.exec_drain(code, timeout=timeout, **kw)
    return nb_outputs(outputs)

# %% ../nbs/01_ops.ipynb #77ab9da4
class EvalError(Exception):
    "An `eval_expr` expression raised in the kernel"

def parse_expr(s):
    "The `literal_eval` of `s` when its form allows, else `s` unchanged"
    try: return literal_eval(s)
    except Exception: return s

@patch
async def user_exprs(self:ConKernelClient, exprs:dict, code:str='', timeout=default_timeout, **kw):
    "Run `code` and evaluate each of the `exprs` expressions in the same round trip; returns the reply content (statuses and mimebundles unparsed)"
    return (await self.execute(code, reply=True, timeout=timeout, user_expressions=exprs, store_history=False, **kw))['content']

@patch
async def eval_expr(self:ConKernelClient, expr:str, code:str='', timeout=default_timeout, **kw):
    "Evaluate `expr` in the kernel (optionally after running `code`) and return its value: parsed via `literal_eval` when its repr allows, else the repr string. Raises `EvalError` if the kernel raises"
    cts = await self.user_exprs({'_': expr}, code, timeout=timeout, **kw)
    if cts['status'] != 'ok': raise EvalError(f"{cts.get('ename')}: {cts.get('evalue')}")
    r = cts['user_expressions']['_']
    if r.get('status') != 'ok': raise EvalError(f"{r.get('ename')}: {r.get('evalue')}")
    return parse_expr(r['data']['text/plain'])

# %% ../nbs/01_ops.ipynb #aafc1ab4
@patch
def shell_request(
    self:ConKernelClient, msg_type, timeout=default_timeout, reply=True, buffers=None,
    msg_id=None, # Override the auto-generated message id
    subshell_id=None, # Route via this subshell (header field)
    metadata=None, # Message metadata (e.g. ipywidgets control-comm version check)
    **content
):
    "Send an arbitrary shell request, routed through the reply reader like `execute`. Returns a coroutine for the reply, or just the msg_id when `reply=False` (for fire-and-forget types like `comm_open` that never get replies)"
    if not self._check_alive(): return asyncio.sleep(0) if reply else None
    msg = self.session.msg(msg_type, content, metadata=metadata)
    if msg_id is not None: msg['header']['msg_id'] = msg_id
    if subshell_id is not None: msg['header']['subshell_id'] = subshell_id
    mid = msg['header']['msg_id']
    if reply: self._pending[mid] = (asyncio.Queue(maxsize=1), False)
    if buffers: self.session.send(self.shell_channel.socket, msg, buffers=buffers)
    else: self.shell_channel.send(msg)
    return self._async_recv_reply(mid, timeout=timeout) if reply else mid

@patch
async def control_request(self:ConKernelClient, msg_type, timeout=default_timeout, **content):
    "Send a request on the control channel and await its matching reply"
    msg = self.session.msg(msg_type, content)
    self.control_channel.send(msg)
    for rem in iter_timeout(timeout):
        try: reply = await self.get_control_msg(timeout=rem)
        except Empty: continue
        if parent_id(reply) == msg['header']['msg_id']: return reply
    raise TimeoutError(f"no reply to {msg_type}")

# %% ../nbs/01_ops.ipynb #4f01d2b6
@patch
async def input_reply(self:ConKernelClient, value:str):
    "Answer the kernel's pending input_request (from `input()` in an execute sent with `allow_stdin=True`)"
    await self.stdin_send(self.session.msg('input_reply', dict(value=value)))

# %% ../nbs/01_ops.ipynb #97d75b1e
class _ReqProxy:
    "Attribute access to protocol requests: `kc.cmd.complete(code=...)` sends `complete_request` on shell"
    def __init__(self, kc, send, suffix='_request'): self.kc,self.send,self.suffix = kc,send,suffix
    def __getattr__(self, name):
        if name.startswith('_'): raise AttributeError(name)
        def _call(*, timeout=default_timeout, **content): return self.send(f"{name}{self.suffix}", timeout=timeout, **content)
        return _call

@patch(as_prop=True)
def cmd(self:ConKernelClient):
    "Shell requests as methods: `await kc.cmd.history(...)` sends `history_request`"
    return _ReqProxy(self, self.shell_request)

@patch(as_prop=True)
def ctl(self:ConKernelClient):
    "Control requests as methods: `await kc.ctl.shutdown(restart=True)` sends `shutdown_request`"
    return _ReqProxy(self, self.control_request)

# %% ../nbs/01_ops.ipynb #af8183ea
class _DapProxy:
    "DAP requests as methods: `kc.dap.stackTrace(threadId=1)` sends a `debug_request` on control"
    def __init__(self, kc): self.kc,self.seq = kc,0
    def __getattr__(self, command):
        if command.startswith('_'): raise AttributeError(command)
        if command.endswith('_') and not command.endswith('__'): command = command[:-1]
        async def _call(*, timeout=default_timeout, full=False, **arguments):
            self.seq += 1
            r = await self.kc.control_request('debug_request', timeout=timeout,
                type='request', seq=self.seq, command=command, arguments=arguments)
            return r if full else r['content']
        return _call

@patch(as_prop=True)
def dap(self:ConKernelClient):
    "DAP debug requests as methods. Stateful (`seq` counter), so cached per client, unlike `cmd`/`ctl`"
    if getattr(self, '_dap', None) is None: self._dap = _DapProxy(self)
    return self._dap

# %% ../nbs/01_ops.ipynb #8b1967f4
@patch
async def interrupt(self:ConKernelClient, timeout=5):
    "Interrupt the running request via `interrupt_request` on control; returns the reply"
    return await self.control_request('interrupt_request', timeout=timeout)

# %% ../nbs/01_ops.ipynb #edaf42c9
@asynccontextmanager
async def run_kernel(
    kernel_name='python3', # Kernelspec name to launch
    manager_cls=ConKernelManager, # Manager class, e.g. a subclass customizing launch
    **kwargs # Passed to `start_kernel` (e.g. `env`, `cwd`)
):
    "Start a kernel, yield `(km, kc)` with channels running, and always shut both down"
    km = manager_cls(kernel_name=kernel_name)
    await km.start_kernel(**kwargs)
    kc = await km.client().start_channels()
    try: yield km, kc
    finally:
        kc.stop_channels()
        await km.shutdown_kernel(now=True)

# %% ../nbs/01_ops.ipynb #839e20f6
async def reconnect(km, kc=None):
    "Restart `km`'s kernel (fresh process, state discarded) and return a newly connected client, stopping `kc` if given"
    if kc is not None: kc.stop_channels()
    await km.restart_kernel(now=True)
    return await km.client().start_channels()
